### ISSUE TITLE
Can't make external stylesheet to work.

### ISSUE THREAD

**Issue by mikaelcedergren** [oscarmorrison/md-page#38]
I'm using this script, but would like an external css file, but can't seem to make it work:

`<link href="custom.css" rel="stylesheet">
<script src="https://rawcdn.githack.com/oscarmorrison/md-page/master/md-page.js"></script><noscript>
## Test`

And the CSS
`h2 {
    color: blue;
}`

The H2 doesn't get the blue color. It generates an H2 tag, but no css attaches to it. The style sheet exists when I checked via the browser. So it seems to find it. What am I missing?

**Comment by p1ho** [comment]
Can you share the link to your file? I can try to see if I can reproduce the problem.

**Comment by mikaelcedergren** [comment]
Actually, it just went through. It took like half an hour, and the css was correct so I'm stumped. I'm using GitHub pages, so maybe there was some sort of caching. At first I wrote h1 instead of h2, and that might have been cached even though directly opening the css showed the correct file. Don't know. I'll close the issue. Thanks for replying though.

**Comment by p1ho** [comment]
Yes, GitHub pages caching is kind of annoying sometimes. I can relate.


Unrelated to this issue but a trick for GitHub pages. From my experience, it's cached by request URI.
This means if you tried to access `https://username.github.io/repo`, it will be cached, but if you access the same page with a slight difference like `https://username.github.io/repo/` or `https://username.github.io/repo/index.html`, because those are technically different URIs, they won't be cached.

**Comment by mikaelcedergren** [comment]
Ah, interesting. Thanks for the tip, very appreciated.
